### ISSUE TITLE
Pretty much not working

### ISSUE THREAD

**Issue by para-dise** [ofarukcaki/dataleaks#14]
Seems to be attempting to insert non-existing values? e.g. "email", "registered" however these field aren't even made in the users table.

Did you upload the wrong SQL files?

Generally can't log-in or sign-up or search, db imported perfectly & credentials work.

**Comment by ofarukcaki** [comment]
There are 2 different databases for both user auth and search results, you may be using the wrong databases. And you better post a screenshot of log of the error

**Comment by mehidhassan** [comment]
I have the same error.
I log in and it redirects me back to the login page.
So what is the solution to this?

**Comment by mehidhassan** [comment]
[Tue Feb 12 20:48:25.150516 2019] [php7:error] [pid 5776:tid 1596] [client 127.0.0.1:59842] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in C:\\xampp\\htdocs\\database.php:2\nStack trace:\n#0 C:\\xampp\\htdocs\\index.php(3): require_once()\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\database.php on line 2
[Tue Feb 12 20:48:26.073568 2019] [php7:error] [pid 5776:tid 1596] [client 127.0.0.1:59842] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in C:\\xampp\\htdocs\\database.php:2\nStack trace:\n#0 C:\\xampp\\htdocs\\index.php(3): require_once()\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\database.php on line 2
[Tue Feb 12 20:48:28.618714 2019] [php7:error] [pid 5776:tid 1596] [client 127.0.0.1:59842] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in C:\\xampp\\htdocs\\database.php:2\nStack trace:\n#0 C:\\xampp\\htdocs\\index.php(3): require_once()\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\database.php on line 2
[Tue Feb 12 20:48:37.289210 2019] [php7:error] [pid 5776:tid 1592] [client 127.0.0.1:59848] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in C:\\xampp\\htdocs\\database.php:2\nStack trace:\n#0 C:\\xampp\\htdocs\\index.php(3): require_once()\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\database.php on line 2
[Tue Feb 12 20:48:37.736236 2019] [php7:error] [pid 5776:tid 1592] [client 127.0.0.1:59848] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in C:\\xampp\\htdocs\\database.php:2\nStack trace:\n#0 C:\\xampp\\htdocs\\index.php(3): require_once()\n#1 {main}\n  thrown in C:\\xampp\\htdocs\\database.php on line 2
[Tue Feb 12 20:49:56.087717 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59894] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:49:56.087717 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59894] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:10.180523 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59900] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:10.180523 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59900] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:21.037144 2019] [php7:notice] [pid 5776:tid 1592] [client 127.0.0.1:59906] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:21.037144 2019] [php7:error] [pid 5776:tid 1592] [client 127.0.0.1:59906] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:27.723526 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:27.723526 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:28.235556 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:28.235556 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:28.450568 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:28.451568 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:28.709583 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:28.709583 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:29.017600 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:29.017600 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:29.292616 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:29.293616 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:29.613635 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:29.613635 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:29.932653 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:29.932653 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:30.168666 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:30.168666 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:30.415680 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:30.415680 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:30.618692 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:30.618692 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:30.832704 2019] [php7:notice] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:30.832704 2019] [php7:error] [pid 5776:tid 1588] [client 127.0.0.1:59907] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:47.391651 2019] [php7:notice] [pid 5776:tid 1592] [client 127.0.0.1:59938] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:47.392651 2019] [php7:error] [pid 5776:tid 1592] [client 127.0.0.1:59938] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:47.925682 2019] [php7:notice] [pid 5776:tid 1592] [client 127.0.0.1:59938] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:47.926682 2019] [php7:error] [pid 5776:tid 1592] [client 127.0.0.1:59938] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:48.189697 2019] [php7:notice] [pid 5776:tid 1592] [client 127.0.0.1:59938] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:48.189697 2019] [php7:error] [pid 5776:tid 1592] [client 127.0.0.1:59938] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:48.560718 2019] [php7:notice] [pid 5776:tid 1592] [client 127.0.0.1:59938] PHP Notice:  Undefined variable: db_site in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/
[Tue Feb 12 20:50:48.560718 2019] [php7:error] [pid 5776:tid 1592] [client 127.0.0.1:59938] PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\\xampp\\htdocs\\login.php:124\nStack trace:\n#0 {main}\n  thrown in C:\\xampp\\htdocs\\login.php on line 124, referer: http://localhost/

**Comment by mehidhassan** [comment]
Fatal error: Uncaught Error: Call to a member function fetchALL() on bool in C:\xampp\htdocs\index.php:127 Stack trace: #0 {main} thrown in C:\xampp\htdocs\index.php on line 127

**Comment by mehidhassan** [comment]
[13-Feb-2019 00:53:47 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /srv/users/mehid1/apps/mhd/public/index.php:1) in /srv/users/mehid1/apps/mhd/public/header.php on line 1

**Comment by ofarukcaki** [comment]
My bad, with latest pull request I accepted the guy changed variable names which I didn't realize.
Now I reverted the repository to an old commit, it should work now.

Clone the repo again and try with this way 👍

**Comment by ofarukcaki** [comment]
@para-dise and @mehidhassan , please let me know if you successfully set it up

**Comment by mehidhassan** [comment]
Yes, worked! Thankyou! <3

**Comment by para-dise** [comment]
Registrations still seem not to be working for me, it says the user has successfully registered yet there's no user in the database.
`Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/c/user/x.tech/public_html/dataleaks/register.php:74) in /home/c/user/x.tech/public_html/dataleaks/header.php on line 1 Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/c/user/x.tech/public_html/dataleaks/register.php:74) in /home/c/user/x.tech/public_html/dataleaks/header.php on line 1
`
Using latest files.
PHP v7

https://i.imgur.com/xUKinFj.png - Users DB specified in connection.php
https://i.imgur.com/m8Tbjt1.png - DB w/ breaches specified in config.php
Again, I'm confused about this line.
` $register = $db_site -> prepare("INSERT INTO users (username,email,password,registered) VALUES(:username,:email,:password,now())");`
the database structure is different from the one specified.

**Comment by para-dise** [comment]
Still not working for me.

`Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/c/claz325/claz325.beget.tech/public_html/dataleaks/register.php:74) in /home/c/claz325/claz325.beget.tech/public_html/dataleaks/header.php on line 1 Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/c/claz325/claz325.beget.tech/public_html/dataleaks/register.php:74) in /home/c/claz325/claz325.beget.tech/public_html/dataleaks/header.php on line 1
`
Cloned latest version.
Again, I'm confused about this line.
`$register = $db_site -> prepare("INSERT INTO users (username,email,password,registered) VALUES(:username,:email,:password,now())");`
The database uploaded doesn't have half of those columns.

My DB specified in config.php: https://i.imgur.com/m8Tbjt1.png
My DB specified in connection.php: https://i.imgur.com/xUKinFj.png

**Comment by mehidhassan** [comment]
You need help? Please send-me your mail or Telegram.
My Telegram Username is: https://t.me/mehidhassan! :)

**Comment by para-dise** [comment]
Sorry lol, I don't have telegram.
paradise_alpaca@riseup.net

**Comment by ofarukcaki** [comment]
I'm closing the issue since it is resolved.

**Comment by para-dise** [comment]
I still don't have a fix but sure lol

**Comment by ofarukcaki** [comment]
@para-dise you have to re-download current version of this repo and install as stated in readme
